dist: xenial
language: java
jdk:
  - openjdk8
sudo: false

cache:
  directories:
  # Cache both Maven's .m2 directory and the installed node modules to speed up build
  - $HOME/.m2
  - $TRAVIS_BUILD_DIR/FrontEnd/node_modules
before_cache:
  - rm -rf $HOME/.m2/repository/com/shmoozed/

before_install:
  # Change into the Backend directory so that Travis can identify dependencies automatically
  - cd BackEnd/shmoozed/

script:
  # Determine whether we are building on master
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "~~~~~~~~~~ TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

  # Perform Backend build
  - echo "%%%%%%%%%%% LAUNCHING BACKEND BUILD %%%%%%%%%%%"
  - mvn clean install

  # Perform Frontend build
  - echo "%%%%%%%%%%% LAUNCHING FRONTEND BUILD %%%%%%%%%%%"
  - cd ../../FrontEnd/
  - npm install
  - npm install -g @angular/cli
  - ng build

  # Deploy Frontend using SCP
  - if [ "$BRANCH" == "master" ]; then echo "%%%%%%%%%%% LAUNCHING FRONTEND DEPLOY %%%%%%%%%%%"; echo "(We aren't actually deploying yet... but that would go here instead of this echo...)"; else echo "%%%%%%%%%%% NOT ON MASTER BRANCH, SKIPPING FRONTEND DEPLOY %%%%%%%%%%"; fi;

# Deploy the Backend to Elasticbeanstalk
deploy:
  # For some weird reason, Travis decides that it is a good idea to blow away everything it made during the build phase... This stops that from happening.
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: AKIAJ25AYVIIHFSCP4IQ
  secret_access_key:
    secure: uCSoSf5Y7uaXVqOce28XWHSX5VjPta0n4v7iGdo0LUMRlqcXosHufXHEp72D/PnOCRp4QzRrTg4SdXwyh+XxWUpFqnUJWMcYnrfkdDur5mxF4A8MhscRJFSQWZcYUMtNC8ur8F4A+1I+It7gt7oU7tLjEBEGq5qb8vWL1TqFogvSElPYsLxyc2NvIeZx2fYsZTJBE40LEYXwSzRUPk8s50xaAlQt3wYXeR74XT0/E/eP8vrJ6GpqHFixAHrGCQH8givyW/fNNVFjE1zmTRshJd3HeetN73Dfv3HRFFPjydqqRARkf/igZyhHOIaZndc5Kq+G9KB1fSr+5NP1APMQS8QWz89MDkvPamak3O6jlAePyPpb1+KutUmugiF3CS3PxEfFK3BB5O58CptKvBGgWinvkhTaKp4+clCnfZ5rCwh2G+6sN0/udsK6Uk78//6RaStokSfNfxpw9H9Yh++aILrBlRRXZd9IbNJYFBUCAxx9DByJzf3l3ZPgqUTTHXCJo8VCAdGzfe9TLGXNuWX90ZQjLQ3K0kudW9Z2hLbIY0t3WlnS4Sr3j4gvAGmQnd9EvUuGD4E3Vt0KyeaIutMsrDgBa9AGvlx3DBkaL52ZdQvCrWfkkdEYdMgfmfN3eNxdQSthisTzV/E9QABwfKizY3/FaAGDrrI7MopK8kn4k+I=
  region: us-east-2
  app: shmoozed-backend-api
  env: ShmoozedBackendApi-env
  bucket_name: elasticbeanstalk-us-east-2-867543728765
  # Although this says "zip_file" it really means "deploy_file" so point it directly at the jar file
  zip_file: '/home/travis/build/cowancs3750fall18/semesterproject-group-2/BackEnd/shmoozed/target/shmoozed-0.3.0.jar'
  on:
    repo: cowancs3750fall18/semesterproject-group-2
    branch: master

