dist: xenial
language: java
jdk:
  - openjdk8
before_install:
  # Change into the Backend directory so that Travis can identify dependencies automatically
  - cd BackEnd/shmoozed/
script:
  # Perform Backend build
  - mvn clean install
  # Perform Frontend build
  - cd ../../FrontEnd/
  - npm install --verbose
  - npm install -g @angular/cli
  - ng build
  # FUTURE - Deploy Frontend using SCP
# FUTURE - Deploy Backend using deploy section
# deploy:
#  provider: elasticbeanstalk
